### PR TITLE
RM-156538 Release 1.0.2

### PR DESCRIPTION
**Pull request by joecotton-wk**
## Purpose

Adding WK CI so that it builds correctly,

## Solution

High level overview of what was done. This is the roadmap for those who are going to CR.

## Semantic Versioning (check one)

- [ ] The following were changed in a non-backward compatible way and requires a major version bump:
  - _[link to the breaking change in the diff]_
- [ ] Something public was added or changed in backward compatible way, this requires a minor version bump
- [x] No public changes nor new features (backwards-compatible refactor or bug fix), so this can be included in a patch
      release

## How to QA

QA:

- [x] `GO111MODULE="off" go build ./...` runs successfully
- [x] `make test` runs successfully
- [x] Build passes
- [x] Skynet passes
- [x] Skynet has test results and the xml file as an artifact
- [x] Aviary passes
- [x] Rosie runs her checks

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
The items listed below may not capture all security relevant changes. Before providing a security review, be sure to review the entire PR for security impact.
<details>
<summary>(1) Security relevant changes were detected</summary>
<li>Watched file <code>aviary.yaml</code> added</li>
</details>

## Action Items
* Request infosec review via Slack: #support-infosec
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by joecotton-wk** [comment]
Hello Rosie, you there?

**Review by jacoblinch-wk — APPROVED** [review]
QA +1

**Review by katherinebishop-wk — APPROVED** [review]
Approving so that hopefully Rosie will remove the `Merge Requirements Unmet` label 🙂

**Comment by joecotton-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
